= InetSoft Docker Images
InetSoft Technology <info@inetsoft.com>
v2021
:doctype: article
:icons: font
:source-highlighter: highlightjs
:toc: left
:tocLevels: 3
:sectlinks:
:imagesdir: images
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[overview]]
== Overview

One initialization image and two service images are provided. The initialization image is intended for use as a sidecar container that performs a one-time configuration that may be customized without creating any new images. The service images are used to run the server and scheduler.

[[init-images]]
== Initialization Images

The three initialization images are:

|===
| Image | Description

| `docker.inetsoft.com/inetsoft/init`
| Initializes the data space.

|===

The initialization image _must_ mount a volume at `/var/lib/inetsoft/shared`. This volume must be shared with the server and scheduler containers.

NOTE: It is strongly recommended that the data space is used in Kubernetes or a clustered deployment in Docker.

See the link:configuration.adoc[configuration document] for details on configuring the initialization image.

[[service-images]]
== Service Images

The two service images are:

|===
| Image | Description

| `docker.inetsoft.com/inetsoft/server`
| The application server.

| `docker.inetsoft.com/inetsoft/scheduler`
| The scheduler.
|===

IMPORTANT: All server, scheduler, and initialization containers _must_ have the `/var/lib/inetsoft/shared` volume mapped to the same persistent storage.

Each scheduler and server container should have the `/var/lib/inetsoft/local/bs` volume mapped to its own persistent storage.

The only environment variables used by these images are:

|===
| Variable | Description | Default Value

| `INETSOFT_MASTER_PASSWORD`
| The master encryption password. Must be the same across all server, scheduler, and initialization containers.
| _None_

| `INETSOFT_MASTER_SALT`
| The master password salt. Only used in FIPS mode.
| _None_

| `JAVA_OPTS`
| Additional command line options for the server Java process.
| `-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -Duser.language=en -Duser.country=US -Djava.locale.providers=COMPAT,SPI`

| `JAVA_CLASSPATH`
| Additional entries to be added to the main classpath of the server. This should be formatted as `path1:path2:path3`.
| _None_
|===
